### ISSUE TITLE
settings page goes fatal error

### ISSUE THREAD

**Issue by Atomin-Lee** [archetyped/simple-lightbox#987]
## Description of Problem
something error when open settings page and it doesnt work on post page.

(Clearly describe the issue you are experiencing here, and fill in the necessary details below)

Fatal error: Uncaught Error: Call to undefined function xml_parser_create() in /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_type.php:305 Stack trace: #0 /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_type.php(210): SLB_Field_Type->parse_layout() #1 /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_type.php(397): SLB_Field_Type->get_layout() #2 /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_type.php(385): SLB_Field_Type->build_layout() #3 /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_collection.php(409): SLB_Field_Type->build() #4 /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_collection.php(769): SLB_Field_Collection->build_items() #5 /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.options.php(664): SLB_Field_Collection->build_group() #6 /data/wordpress/wp-admin/includes/template.php(1409): SLB_Options->admin_build_group() #7 /data/wordpress/wp-content/plug in /data/wordpress/wp-content/plugins/simple-lightbox/includes/class.field_type.php on line 305
## Details

* URL of Page exhibiting problem: 
* Browser(s) exhibiting problem (Firefox, Chrome, etc.): 
* Version of SLB Installed: 2.9.3
* Other plugins installed: Astra, no jquery needed.

**Comment by Atomin-Lee** [comment]
sorry, i did not install php74-php-xml
